"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 18:04:07.419229
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = (
    "profiles",
    "health_profiles",
    "invitations",
    "caregiver_grants",
    "collector_devices",
    "ingest_batches",
    "source_records",
    "measurements",
    "sync_runs",
    "check_ins",
    "rules",
    "alerts",
    "push_devices",
    "notification_outbox",
    "audit_events",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_health_profile_id"),
        "audit_events",
        ["health_profile_id"],
        unique=False,
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("monitoring_enabled", sa.Boolean(), nullable=False),
        sa.Column("data_mode", sa.String(length=16), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("preferred_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("data_mode in ('live','simulation')", name="ck_health_profiles_mode"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_profiles_owner_user_id"), "health_profiles", ["owner_user_id"], unique=False
    )
    op.create_table(
        "push_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.String(length=64), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("last_registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_reason", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "installation_id", name="uq_push_install"),
    )
    op.create_index(op.f("ix_push_devices_user_id"), "push_devices", ["user_id"], unique=False)
    op.create_table(
        "check_ins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "checked_in_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_check_ins_health_profile_id"), "check_ins", ["health_profile_id"], unique=False
    )
    op.create_table(
        "collector_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_upload_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("health_profile_id", "installation_id", name="uq_collector_install"),
    )
    op.create_index(
        op.f("ix_collector_devices_health_profile_id"),
        "collector_devices",
        ["health_profile_id"],
        unique=False,
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by", sa.UUID(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["claimed_by"], ["profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_invitations_health_profile_id"), "invitations", ["health_profile_id"], unique=False
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=True),
        sa.Column("threshold_value", sa.Float(), nullable=True),
        sa.Column("recovery_value", sa.Float(), nullable=True),
        sa.Column("window_minutes", sa.Integer(), nullable=False),
        sa.Column("min_samples", sa.Integer(), nullable=False),
        sa.Column("max_gap_minutes", sa.Integer(), nullable=False),
        sa.Column("freshness_minutes", sa.Integer(), nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("reminder_minutes", sa.Integer(), nullable=True),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("baseline_min_days", sa.Integer(), nullable=False),
        sa.Column("baseline_lookback_days", sa.Integer(), nullable=False),
        sa.Column("deviation_threshold", sa.Float(), nullable=False),
        sa.Column("deviation_floor", sa.Float(), nullable=True),
        sa.Column("is_synthetic_demo", sa.Boolean(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rules_health_profile_id"), "rules", ["health_profile_id"], unique=False
    )
    op.create_table(
        "source_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("data_origin", sa.String(length=255), nullable=False),
        sa.Column("record_type", sa.String(length=64), nullable=False),
        sa.Column("source_record_id", sa.String(length=128), nullable=False),
        sa.Column("record_version", sa.BigInteger(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("zone_offset_seconds", sa.Integer(), nullable=True),
        sa.Column("device", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recording_method", sa.String(length=32), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_backfill", sa.Boolean(), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("first_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "health_profile_id",
            "data_origin",
            "record_type",
            "source_record_id",
            name="uq_source_record",
        ),
    )
    op.create_index(
        "ix_source_records_profile_srcid",
        "source_records",
        ["health_profile_id", "source_record_id"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("rule_config_version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("episode_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminders_sent", sa.Integer(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_reason", sa.String(length=64), nullable=True),
        sa.CheckConstraint("status in ('open','acknowledged','resolved')", name="ck_alerts_status"),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_id"], ["rules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("health_profile_id", "episode_key", name="uq_alert_episode"),
    )
    op.create_index(
        op.f("ix_alerts_health_profile_id"), "alerts", ["health_profile_id"], unique=False
    )
    op.create_index(
        "uq_alert_open_per_rule",
        "alerts",
        ["rule_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.create_table(
        "caregiver_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("caregiver_user_id", sa.UUID(), nullable=False),
        sa.Column("invitation_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("consent_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status in ('pending','active','revoked')", name="ck_grants_status"),
        sa.ForeignKeyConstraint(["caregiver_user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invitation_id"], ["invitations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_caregiver_grants_caregiver_user_id"),
        "caregiver_grants",
        ["caregiver_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_caregiver_grants_health_profile_id"),
        "caregiver_grants",
        ["health_profile_id"],
        unique=False,
    )
    op.create_index(
        "uq_grants_live_pair",
        "caregiver_grants",
        ["health_profile_id", "caregiver_user_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'revoked'"),
    )
    op.create_table(
        "ingest_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("collector_device_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collector_device_id"], ["collector_devices.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingest_batches_health_profile_id"),
        "ingest_batches",
        ["health_profile_id"],
        unique=False,
    )
    op.create_table(
        "measurements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_record_id", sa.UUID(), nullable=False),
        sa.Column("health_profile_id", sa.UUID(), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("sample_index", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_origin", sa.String(length=255), nullable=False),
        sa.Column("is_backfill", sa.Boolean(), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "value <> 'NaN'::float8 AND value <> 'Infinity'::float8 AND value <> '-Infinity'::float8",
            name="ck_measurements_finite",
        ),
        sa.ForeignKeyConstraint(["health_profile_id"], ["health_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_record_id", "metric", "sample_index", name="uq_measurement"),
    )
    op.create_index(
        "ix_measurements_profile_metric_time",
        "measurements",
        ["health_profile_id", "metric", "measured_at"],
        unique=False,
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collector_device_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("metrics_found", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint", sa.String(length=64), nullable=True),
        sa.Column("error_category", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collector_device_id"], ["collector_devices.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_runs_collector_device_id"), "sync_runs", ["collector_device_id"], unique=False
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("alert_id", sa.UUID(), nullable=False),
        sa.Column("recipient_user_id", sa.UUID(), nullable=False),
        sa.Column("push_device_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("discarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discard_reason", sa.String(length=64), nullable=True),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["push_device_id"], ["push_devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "alert_id", "recipient_user_id", "push_device_id", "sequence", name="uq_outbox_job"
        ),
    )
    op.create_index(
        "ix_outbox_due",
        "notification_outbox",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("accepted_at IS NULL AND discarded_at IS NULL"),
    )
    # ### end Alembic commands ###

    # --- Defence in depth: clients must not bypass the API's grant checks. -------------
    # RLS enabled with NO policies = deny-all for any non-owner role (e.g. Supabase's
    # PostgREST 'anon' / 'authenticated'). The backend connects as the table owner.
    for table in TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    op.execute(
        """
        DO $$
        DECLARE r text;
        BEGIN
          FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
              EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', r);
              EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', r);
            END IF;
          END LOOP;
        END $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_due",
        table_name="notification_outbox",
        postgresql_where=sa.text("accepted_at IS NULL AND discarded_at IS NULL"),
    )
    op.drop_table("notification_outbox")
    op.drop_index(op.f("ix_sync_runs_collector_device_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index("ix_measurements_profile_metric_time", table_name="measurements")
    op.drop_table("measurements")
    op.drop_index(op.f("ix_ingest_batches_health_profile_id"), table_name="ingest_batches")
    op.drop_table("ingest_batches")
    op.drop_index(
        "uq_grants_live_pair",
        table_name="caregiver_grants",
        postgresql_where=sa.text("status <> 'revoked'"),
    )
    op.drop_index(op.f("ix_caregiver_grants_health_profile_id"), table_name="caregiver_grants")
    op.drop_index(op.f("ix_caregiver_grants_caregiver_user_id"), table_name="caregiver_grants")
    op.drop_table("caregiver_grants")
    op.drop_index(
        "uq_alert_open_per_rule",
        table_name="alerts",
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.drop_index(op.f("ix_alerts_health_profile_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_source_records_profile_srcid", table_name="source_records")
    op.drop_table("source_records")
    op.drop_index(op.f("ix_rules_health_profile_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_invitations_health_profile_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_collector_devices_health_profile_id"), table_name="collector_devices")
    op.drop_table("collector_devices")
    op.drop_index(op.f("ix_check_ins_health_profile_id"), table_name="check_ins")
    op.drop_table("check_ins")
    op.drop_index(op.f("ix_push_devices_user_id"), table_name="push_devices")
    op.drop_table("push_devices")
    op.drop_index(op.f("ix_health_profiles_owner_user_id"), table_name="health_profiles")
    op.drop_table("health_profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_audit_events_health_profile_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
